#!/bin/bash

commit_count=$(git rev-list --count HEAD)
step=$(expr $commit_count - 1 - $1)
git checkout master
git reset --hard origin/master
git clean -d -f
git reset --hard HEAD~$step
git reset --soft HEAD~1
git reset
